sudo: false
language: ruby

cache: bundler

script:
  - bundle exec rake lint
  - bundle exec rake validate
  - bundle exec rake spec

matrix:
  fast_finish: true

  include:
    # Unit tests
    - rvm: 2.5.7
      env: PUPPET_GEM_VERSION='~> 4.0'
    - rvm: 2.6.5
      env: PUPPET_GEM_VERSION='~> 4.0'
    - rvm: 2.7.0
      env: PUPPET_GEM_VERSION='~> 4.0'

    # Acceptance tests
    - rvm: default
      sudo: required
      services: docker
      env: BEAKER_set=centos-6-x64
      script: bundle exec rake beaker
    - rvm: default
      sudo: required
      services: docker
      env: BEAKER_set=ubuntu-14.04-x64
      script: bundle exec rake beaker
    - rvm: default
      sudo: required
      services: docker
      env: BEAKER_set=debian-9-x64
      script: bundle exec rake beaker

notifications:
  email: false
