name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [dummy]
        ruby-version: [dummy]
        puppet-version: [dummy]
        check: [dummy]
        include:
          - os: ubuntu-16.04
            ruby-version: 2.6
            puppet-version: '~> 6.0'
            check: ''
          - os: ubuntu-18.04
            ruby-version: 2.6
            puppet-version: '~> 6.0'
            check: ''
          - os: ubuntu-20.04
            ruby-version: 2.6
            puppet-version: '~> 6.0'
            check: ''
          - os: ubuntu-18.04
            ruby-version: 2.6
            puppet-version: '~> 6.0'
            check: 'syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop'
          - os: ubuntu-18.04
            ruby-version: 2.3.8
            puppet-version: '~> 4.0'
            check: parallel_spec
          - os: ubuntu-18.04
            ruby-version: 2.4.9
            puppet-version: '~> 5.0'
            check: parallel_spec
          - os: ubuntu-18.04
            ruby-version: 2.5.7
            puppet-version: '~> 5.0'
            check: parallel_spec
        exclude:
          - os: dummy
            ruby-version: dummy
            puppet-version: dummy
            check: dummy
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
      env:
        PUPPET_GEM_VERSION: ${{ matrix.puppet-version }}
    - name: Run tests
      run: bundle exec rake $CHECK
      env:
        CHECK: ${{ matrix.check }}
  centos:
    runs-on: ubuntu-latest
    container: ghcr.io/k1low/centve:latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      run: |
        anyenv-init
        rbenv global 2.7.3
    - name: Run tests
      run: |
        gem install bundler
        bundle exec rake
